name: interview_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Core
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  fpdart: ^1.1.0

  #Network
  dio: ^5.4.0

  #Dependency injection
  injectable: ^2.3.2
  get_it: ^7.6.4

  # Lang dependencies
  intl: ^0.19.0

  #Loggin
  pretty_dio_logger: ^1.3.1

  #Data persistence
  get_storage: ^2.1.1

  #Routing
  go_router: ^13.0.1

  #Presentation
  flutter_svg: ^2.0.9

dev_dependencies:
  mocktail: 1.0.4
  bloc_test: ^9.1.7

  flutter_test:
    sdk: flutter

  build_runner: ^2.4.8
  injectable_generator: ^2.3.2
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/

  fonts:
    - family:  ForemostIcons
      fonts:
       - asset: assets/fonts/foremost_icons.ttf


